= Documentation as Code: Script

// .TODO
// - code friendly; built-in support for highlighted source blocks

🗣 (mode narrateur)
👨 Mon père (en mode dialogue)
👶 Moi (en mode dialogue)

[#true-story]
#musique au coin du feu#
🗣 Le week-end dernier, notre personnage principal s'est rendu chez son père Bernard...

[#story-coffee]
🗣 C'est autour d'un café bien chaud que la discussion commence.
🗣 Ça papote, ça papote...

[#story-christmas-tree]
👶 Ah t'as déjà installé ton sapin ? C'est joli !
🗣 Son père lui montre fièrement sa nouvelle cheminée :

[#story-fireplace]
--
👨 T'as vu bla bla bla, elle est super !

* bla bla chaleur
* bla bla bûches...

#tête faisant semblant d'être intéressé#
--

[#story-whatsup]
👶 Bon et sinon quoi de neuf ?

[#story-book-unknown]
👨 En bien en ce moment, je travaille sur mon nouveau livre.
👶 Ah ouais cool, c'est sur quoi ?

[#story-book-longevity]
👨 C'est sur la longévité.
👨 J'avais envoyé mon premier chapitre à l'éditeur et là je viens de recevoir les corrections.

[#story-firehair]
🗣 Notre protagoniste à la crinière de feu est intrigué.

[#story-editor-collaboration]
👶 Mais du coup, ça marche comment avec ton éditeur ?
👶 Vous gérez comment les échanges ?

[#story-word]
👨 Et bien, je rédige mon chapitre dans un document Word,

[#story-email]
👨 je lui envoie par email et ensuite elle me renvoie le document revu et corrigé.

[#story-edit-question]
👶 Elle édite directement le document ?

[#story-word-revisions]
👨 Non, enfin, elle utilise les *marques de révision* pour les corrections et les commentaires pour les questions et autres remarques.
👨 Je n'ai plus qu'à accepter et/ou refuser les corrections et tenir comptes de ses remarques.
👨 On dirait pas comme ça mais ça prends du temps tu sais.

[#story-force-awakens]
#raconté comme une scène d'actions plein de péripéties#
🗣 À cet instant précis de notre histoire, une force interieure réveille notre héro.
🗣 C'est plus fort que lui.

[#story-brain-falpie-zone]
🗣 La zone FALPIE* de son cerveau s'active.
// * Firefox A La Place d'Internet Explorer
🗣 Et oui, la dernière fois c'était *Noël 2006* :
🗣 Voyant IE6 dominer l'ordi de ses parents, il n'a pu s'empêcher de les libérer en installant Firefox à la place.

[#story-dangers]
--
🗣 Cette fois ci, les facteurs déclencheurs sont :

#raconté comme des dangers#

* Écriture avec MS Word !
* Collaboration par email !
--

[#story-ending]
#alexandrin#
🗣 Un-e nou-vel-le chose à no-tre roux s'im-pose :
🗣 ex-pli-qu-er_à son père sa "bonne façon" de faire.

[#title]
--
// ce slide a besoin d'être découpé
#mode normal (et énergique)#

Bonjour à tous !
J'm'appelle Hubert Sablonnière,
J'suis développeur Web chez OpenDevise
et aujourd'hui j'ai envie d'vous parler de *Documentation as code*
#pause#
et de mon père !

*Documentation as code* : Tout simplement parceque chez OpenDevise on aide nos clients à adopter ce modèle pour leur documentation.
--

[#docs-eq-code]
--
L'idée générale est de traiter la doc comme du code en réutilisant des outils et des pratiques bien connues des développeurs et des ops.
Ça ne se limite pas qu'à la documentation d'ailleurs.
On pousse nos clients à envisager cette approche pour tous leurs contenus pédagogiques : livres, formations, présentations dans les conférences...
--

[#my-father]
Si j'ai *aussi* envie de vous parler de mon père,
c'est parce qu'en plus de son métier d'enseignant-chercheur en médecine,
un peu comme nous, il a des side-projects !

[#my-father-books]
--
Depuis 2010, il a "mis en prod" sur son temps libre pas moins de 6 bouquins de vulgarisation.

En plus, c'est pas vraiment un geek.
Il utilise son ordinateur comme tout le monde.
Il représente du coup, l'exemple parfait du client néophyte et sceptique au concept de Doc as code.
--

[#macho]
Bon et au passage, on est plus dans les années 60, donc si on pouvait éviter les articles ou les présenations du genre "Documentation as Code (expliqué à ma mère)", sans que ça n'ai de rapport, ça serait mieux.

[#writing-preamble]
--
Du coup, en discutant avec lui le week-end dernier,
j'étais assez curieux de voir les points communs et les différences entre les livres sur lesquels il travaille et la documentation technique sur laquelle on travaille nous dans notre domaine.
Je voulais en savoir plus sur sa méthode et surtout lui expliquer comment un cerveau de dev fonctionne lorsqu'il s'agit de faire vivre une documentation.
--

== Écriture

[#writing]
--
// ajouter les remarques de Dan

// I thought of a lead in for the publishing section of the talk so as to keep the writers engaged.
// "Writers, now don't tune out. This is when you get to see the fruits of your labor emerge. The engineers are tasked with making your words look awesome. You'll also find out about a little bonus that feeds back into your writing workflow." (that bonus is the "review site", which allows writers to preview the published site in a staging area, get in the readers' shoes, and be able to take those impressions back to the writing phase).
//
// Dan Allen @mojavelinux 01:29
// As Sarah just put it to me, this is really about building empathy.
// We can't have a format that is good for one group that isn't good for the other.
// The first part (writing) helps engineers build empathy for the writers and their needs.
// The last part (publishing) helps writers build empathy for the engineers and their needs.
// So they have a reason for using AsciiDoc beyond their own needs.
// And of course, the collaboration section in the middle shows that this format allows them to work together and shows them how they can.
// this structure for that talk gives it meaning. now it really says something about the why this system is needed and why it works.

Le premier sujet que j'ai abordé avec lui, c'est l'écriture.

Il passe beaucoup de temps à lire et à prendre des notes sur papier,
mais globalement, il écrit directement avec Word sur son ordinateur portable.

#Chuchotte#
Il tape à 2 doigts !!
// je tape à 6 doigts
--

[#word-styles]
Le premier truc qui m'a surpris, c'est le fait qu'il n'utilise pas du tout le système de styles du genre "Corps de texte", "Titre 1", "Titre 2"...

[#semantic-conventions]
--
En fait, son éditeur lui fournit une série de conventions pour identifier les différentes parties de son texte :

* Pour les titres et autres sous-titres, il doit utiliser différentes tailles de texte bien précises,
* Pour les citations qu'il met en début de chapitre, il doit utiliser de l'italique,
* et pour les encarts, il doit utiliser une police différente.

Et là, ça fait tilt !
--

[#separation-of-concerns]
--
J'pense tout d'suite au principe de "Séparation des préoccupations..."
https://en.wikipedia.org/wiki/Separation_of_concerns[SoC : Separation of Concerns]

Je lui explique un peu, c'est un principe qu'on retrouve :

* côté réseau avec les différentes couches du modèle OSI
* côté dev avec différents patterns comme le MVC par exemple
* mais aussi côté Web avec la triforce : HTML + CSS + JS

Moi, ça me rappelle mes débuts en CSS.
C'est la première fois que je séparais :
--

[#content-vs-presentation]
--
* le contenu et sa sémantique d'un côté
* et la présentation, le style, la décoration de l'autre.

A l'époque quand je voulais vanter les mérites de CSS et de la séparation contenu/présentation en général,
--

[#css-zen-garden]
--
je montrais le site http://www.csszengarden.com/[CSS Zen Garden] !

Il y a énormément d'avantages à appliquer cette pratique notamment pour la partie publication.
On y reviendra plus tard.
--

[#content-is-priority-1]
--
Concernant l'écriture, cette séparation permet de mettre la priorité sur le contenu.
On va libèrer l'auteur en lui permettant de d'uploader les idées qu'il a dans son cerveau le plus rapidement possible dans l'ordinateur.
Le contenu doit être roi !
--

[#html]
--
maybe I should introduce him to HTML?

imagine for a moment him writing in HTML
it doesn't feel like a writing language
and why would I use the output for a webpage while I want to write a book
--

[#book-as-html]
--
html
so imagine there was a language for writing books...
--

[#docbook-ex-1]
Anyone recognize this?
Anyone like it?
This is DocBook.

[#docbook]
--
My dad would struggle to learn so much stuffs about the XML strict rules instead of focusing on writing

DocBook is an XML schema that's highly structured and semantic with a keen focus on separating content and presentation.
So far, so good, right?
--

[#docbook-ex-2]
--
Oh, you thought that was it?
//SAW: visual concept - image of a knotted mess or massive, sticky web/goo
As a writer, would you want to weave your content in and out of this web day-in and day-out?
Yeah, I didn't think so.

You have to enclose every chunk of content in an envelope of markup.
Your content gets shackled by this heavy structure.
And there's the added burden of having to remember all the tags and when to use each of them.

The ironic part is that the engineer didn't do herself much of a favor either.
XML tools--especially the ones used in the DocBook toolchain, such as XSLT--are a pain to work with.

Nobody wins.
//SAW: visual concept - image meme opposite of winning
--


[#latex-ex-1]
//Moving on, how about this?
How about this?
Clearly, the engineer was having fun while the writer was away.
This is LaTeX (LAH-tekh).

[#latex]
LaTeX is a documentation preparation system (read as: low-level language) for high-quality typesetting widely used in academia.

[#latex-ex-2]
--
!!! LaTeX have many differences and dialects

The message here--if you can even interpret it--is:
"`I don't really see the difference between content, typesetting, and presentation, so I'll just mash all these concerns together.`"

Writers get lost in this syntax, not only because it looks like a bird nest, but now there's this deluge of dialects no mere mortal can possibly remember.
//SAW: image concept - labrynth/maze which matches the "get lost" concept

The other major issue with LaTeX is that is was not designed with web publishing in mind.
PDF anyone?
You're options are limited even before you've begun.

The point is that many content systems cater more--even exclusively--to the technologist rather than to the writer.

This situation has _got_ to change.
That's where AsciiDoc comes in to save the day.
--

[#asciidoc-ex]
How about this instead?
This is AsciiDoc.

[#asciidoc-fox-approves]
//The fox likes it.
Mmmm.

[#asciidoc]
We created AsciiDoc as a writer-centric markup system.
And it shows.
The reaction many writers have when they switch to this syntax is, "`I can finally see my content!`"
That speaks volumes.

// concise * consistent * semantic
[#asciidoc-qualities]
--
//LAR: Can we have a series of example slides as you go through this list of benefits?
//LAR: That would be more informative and engaging.
//LAR: I'm not wild about the highlighted list because it isn't "showing" what you're talking about, which is the point, right?
//LAR: Slides that show the AsciiDoc version and what is created (like the reference manual) would be great.
The first thing you'll notice about AsciiDoc is that the syntax is clear & concise.
//LAR: a slide here of the syntax that shows what you mean.
What you see is predominantly content.
It's readable in raw form, unlike the other formats we've seen thus far.

//LAR: Is this quote necessary?
//LAR: Maybe make it a slide and move it to the end of this section?
//SAW: Agree with LAR, the quote, while applicable, isn't needed and probably breaks the flow of the narrative.
//"#Perfection is achieved not when there's nothing more to add, but when there's nothing left to take away.#"
//-- Antoine de Saint-Exubéry

Paragraphs are just paragraphs, no bullshit.
//LAR: give me an example slide.
The remaining marks are based on familiar conventions, such as leading asterisks to itemize a list, asterisks or underscores around a phrase to emphasize it, and leading equal signs to designate a section title.
//LAR: another slide example.
Keywords that appear in the syntax are based on common terminology such as `image`, `video`, and `source`.

And the syntax is remarkably forgiving, which makes it less daunting for first timers.

If you dig deeper, you'll notice a consistency to the syntax.
That's because the language is based on repeatable patterns.
Extensions further build on these patterns, which we'll get into later.

Finally, the syntax is extremely semantic.
In fact, AsciiDoc was originally designed as a shorthand for DocBook.
Each bit of content belongs to a node--a content block or phrase.
Nodes can be annotated with extra bits of information that state what the content is, how it might be presented, and other properties.
//SAW: we definitely want an example slide of this.
--

[#ex-roles]
--
The most versatile semantic information is the role.

Roles serve a very important purpose in the AsciiDoc syntax because they allow the writer to pass information to the publisher about the semantics of a node without having to worry how it gets formatted.
The role basically says "`this element has special significance, you deal with it.`"
This abtraction, and other such metadata, is central to achieving the separation of content and presentation.
The writer gets to focus on what the content is saying, not how it looks.
--

//DA: QUESTION should the point about line-oriented/left-align go right at beginning, before other characteristics?
[#left-aligned-lines]
One reason the syntax is so simple and consistent is because it's both line-oriented and left-aligned.

//DA: TODO follow-up with an example of left-align and line-oriented
[#ex-delimited-block]
--
Having a syntax that's aligned to the left margin helps keeps the writer rooted.
You don't have to worry how much indentation you need and content doesn't float out into the ether.
Instead, you rely on delimiter lines, or "`fences`" to encompass the content.
AsciiDoc can then assume everything between those lines is content that belongs to that block.

//The line-oriented arrangement takes advantage of the fact that source code is organized in lines.
//A lot can be inferred from a line break in the content.
The line-oriented arrangements allows us use the line break to imply meaning.
A line often serves as the boundaries of a node.
Consecutive lines that start with an asterisk, for instance, are clearly items in a list.
A line above a block that starts with a period is the block's title.
We do the same thing when writing code.
Each statement gets its own line, so there's no need for a semicolon to separate statements.

Asciidoc
  clair & concis
    ex: général
  paragraphes
    ex: paragraphes (one line per sentence compared to )
  conventions familières
    ex: titres
    ex: liste à puce
    ex: gras/italic...
  => un peu comme markdown, mouais mais en mieux
  terminologie commune
    ex: image, video, source
    consistence, pattern répétés et extensions
    syntax souple (forgiving)
  sémantique
  left-aligned

no wysiwyg
  CMS pb
you get what you get
  CMS, wikis

IDE for writers
  stop thinking about what we had before and
  think about tools

Atom
  un peu de syntaxe
  emphasise on coloration
  syntax highlighting code blocks
  mode preview
  WHAT ELSE COULD WE DO?
  quelques techniques de codeurs
    variables/attributes
    includes
    autocomplétion
    réordonner des lignes
    regexs
    ...autres
  zen mode

// à triver
roles ?
1 sentence per line (maybe collaboration)
footnote ?

--
