= Documentation as Code: Script

// .TODO
// - code friendly; built-in support for highlighted source blocks

🗣 (mode narrateur)
👨 Mon père (en mode dialogue)
👶 Moi (en mode dialogue)

[#true-story]
#musique au coin du feu#

[#true-story-start]
🗣 Le week-end dernier, notre personnage principal s'est rendu chez son père Bernard...

[#story-coffee]
🗣 C'est autour d'un café bien chaud que la discussion commence.
🗣 Ça papote, ça papote...

[#story-christmas-tree]
👶 Ah t'as déjà installé ton sapin ? C'est joli !
🗣 Son père lui montre fièrement sa nouvelle cheminée :

[#story-fireplace]
--
👨 T'as vu bla bla bla, elle est super !

* bla bla chaleur
* bla bla bûches...

#tête faisant semblant d'être intéressé#
--

[#story-whatsup]
👶 Bon et sinon quoi de neuf ?

[#story-book-unknown]
👨 En bien en ce moment, je travaille sur mon nouveau livre.
👶 Ah ouais cool, c'est sur quoi ?

[#story-book-longevity]
👨 C'est sur la longévité.
👨 J'avais envoyé mon premier chapitre à l'éditeur et là je viens de recevoir les corrections.

[#story-firehair]
🗣 Notre protagoniste à la crinière de feu est intrigué.

[#story-editor-collaboration]
👶 Mais du coup, ça marche comment avec ton éditeur ?
👶 Vous gérez comment les échanges ?

[#story-word]
👨 Et bien, je rédige mon chapitre dans un document Word,

[#story-email]
👨 je lui envoie par email et ensuite elle me renvoie le document revu et corrigé.

[#story-edit-question]
👶 Elle édite directement le document ?

[#story-word-revisions]
👨 Non, enfin, elle utilise les *marques de révision* pour les corrections et les commentaires pour les questions et autres remarques.
👨 Je n'ai plus qu'à accepter et/ou refuser les corrections et tenir comptes de ses remarques.
👨 On dirait pas comme ça mais ça prends du temps tu sais.

[#story-force-awakens]
#raconté comme une scène d'actions plein de péripéties#
🗣 À cet instant précis de notre histoire, une force interieure réveille notre héro.
🗣 C'est plus fort que lui.

[#story-brain]
🗣 La zone FALPIE* de son cerveau s'active.
// * Firefox A La Place d'Internet Explorer
🗣 Et oui, la dernière fois c'était *Noël 2006* :

[#story-brain-falpie-zone]
🗣 Voyant IE6 dominer l'ordi de ses parents, il n'a pu s'empêcher de les libérer en installant Firefox à la place.

[#story-dangers-safe]
🗣 Cette fois ci, il est menacé par :
#raconté comme des dangers#

[#story-dangers]
--
* l'écriture avec MS Word !
--

[#story-dangers-mute]
--
--

[#story-dangers-two]
--
* Collaboration par email !
--


[#story-ending]
#alexandrin#
🗣 Un-e nou-vel-le chose à no-tre roux s'im-pose :
🗣 ex-pli-qu-er_à son père sa "bonne façon" de faire.

[#title]
--
// ce slide a besoin d'être découpé
#mode normal (et énergique)#

Bonjour à tous !
J'm'appelle Hubert Sablonnière,
J'suis développeur Web chez OpenDevise
et aujourd'hui j'ai envie d'vous parler de *Documentation as code*
#pause#
et de mon père !

*Documentation as code* : Tout simplement parceque chez OpenDevise on aide nos clients à adopter ce modèle pour leur documentation.
--

[#docs-eq-code]
--
L'idée générale est de traiter la doc comme du code en réutilisant des outils et des pratiques bien connues des développeurs et des ops.
Ça ne se limite pas qu'à la documentation d'ailleurs.
On pousse nos clients à envisager cette approche pour tous leurs contenus pédagogiques : livres, formations, présentations dans les conférences...
--

[#my-father]
--
Si j'ai *aussi* envie de vous parler de mon père,
c'est parce qu'en plus de son métier d'enseignant-chercheur en médecine,
un peu comme nous, il a des side-projects !

// [#my-father-books]
// --
Depuis 2010, il a "mis en prod" sur son temps libre pas moins de 6 bouquins de vulgarisation.

En plus, c'est pas vraiment un geek.
Il utilise son ordinateur comme tout le monde.
Il représente du coup, l'exemple parfait de l'auteur/écrivain/rédacteur agnostique au concept de Docs as code.
--

[#macho]
Bon et au passage, on est plus dans les années 60, donc si on pouvait éviter les articles ou les présenations du genre "Documentation as Code (expliqué à ma mère)", sans que ça n'ai de rapport, ça serait mieux.

[#writing-preamble]
--
Du coup, en discutant avec lui le week-end dernier,
j'étais assez curieux de voir les points communs et les différences entre les livres sur lesquels il travaille et la documentation technique sur laquelle on travaille nous dans notre domaine.
Je voulais en savoir plus sur sa méthode et surtout lui expliquer comment un cerveau de dev fonctionne lorsqu'il s'agit de faire vivre une documentation.
--

== Écriture

[#writing]
--
// ajouter les remarques de Dan

// I thought of a lead in for the publishing section of the talk so as to keep the writers engaged.
// "Writers, now don't tune out. This is when you get to see the fruits of your labor emerge. The engineers are tasked with making your words look awesome. You'll also find out about a little bonus that feeds back into your writing workflow." (that bonus is the "review site", which allows writers to preview the published site in a staging area, get in the readers' shoes, and be able to take those impressions back to the writing phase).
//
// Dan Allen @mojavelinux 01:29
// As Sarah just put it to me, this is really about building empathy.
// We can't have a format that is good for one group that isn't good for the other.
// The first part (writing) helps engineers build empathy for the writers and their needs.
// The last part (publishing) helps writers build empathy for the engineers and their needs.
// So they have a reason for using AsciiDoc beyond their own needs.
// And of course, the collaboration section in the middle shows that this format allows them to work together and shows them how they can.
// this structure for that talk gives it meaning. now it really says something about the why this system is needed and why it works.

Le premier sujet que j'ai abordé avec lui, c'est l'écriture.

// Qu'on parle de livre, de documentation, d'article... quel que soit le media, les problématiques des auteurs sont souvent les mêmes.

Il passe beaucoup de temps à lire et à prendre des notes sur papier,
mais globalement, il écrit directement avec Word sur son ordinateur portable.

#Chuchotte#
Il tape à 2 doigts !!
// je tape à 6 doigts
--

[#word-styles]
Le premier truc qui m'a surpris, c'est le fait qu'il n'utilise pas du tout le système de styles du genre "Corps de texte", "Titre 1", "Titre 2"...

[#semantic-conventions]
--
En fait, son éditeur lui fournit une série de conventions pour identifier les différentes parties de son texte :

* Pour les titres et autres sous-titres, il doit utiliser différentes tailles de texte bien précises,
* Pour les citations qu'il met en début de chapitre, il doit utiliser de l'italique,
* et pour les encarts, il doit utiliser une police différente.

Et là, ça fait tilt !
--

[#separation-of-concerns]
--
J'pense tout d'suite au principe de "Séparation des préoccupations..."
https://en.wikipedia.org/wiki/Separation_of_concerns[SoC : Separation of Concerns]

Je lui explique un peu, c'est un principe qu'on retrouve :

* côté réseau avec les différentes couches du modèle OSI
* côté dev avec différents patterns comme le MVC par exemple
* mais aussi côté Web avec la triforce : HTML + CSS + JS

Moi, ça me rappelle mes débuts en CSS.
C'est la première fois que je séparais :
--

[#content-vs-presentation]
--
* le contenu et sa sémantique d'un côté
* et la présentation, le style, la décoration de l'autre.

A l'époque quand je voulais vanter les mérites de CSS et de la séparation contenu/présentation en général,
--

[#css-zen-garden]
--
je montrais le site http://www.csszengarden.com/[CSS Zen Garden] !

Il y a énormément d'avantages à appliquer cette pratique notamment pour la partie publication.
On y reviendra plus tard.
--

[#content-is-priority-1]
--
Concernant l'écriture, cette séparation permet de mettre la priorité sur le contenu.
Sur ce qu'il est et qu'il transmet.
--

[#brain-to-machine]
--
On va libèrer l'auteur en lui permettant de d'uploader ses idées (qu'il a dans son cerveau) le plus rapidement possible dans l'ordinateur.
--

[#html]
--
Du coup au départ, je voulais parler d'HTML à mon père pour qu'il écrive ses livres,
mais je me suis dis, même moi qui connais bien le langage,
--

[#book-as-html]
--
je ne voudrais pas écrire tout un livre avec ça.
C'est pas du binaire, ok, un humain peut le lire et l'écrire.
J'ai essayé d'écrire des articles ou de la doc directement avec mais c'est vraiment pas pratique.
// Il faudrait que je lui explique toutes les règles liées aux balises, aux attributs.

// imagine for a moment him writing in HTML
// it doesn't feel like a writing language
// and why would I use the output for a webpage while I want to write a book
// html
// so imagine there was a language for writing books...
--

[#book-as-html-2]
--
C'est pas avec ça qu'on va simplifier le chemin cerveau-machine.
En plus, hormis quelques bonnes exceptions, HTML est majoritairement fait pour les navigateurs et pas vraiment pour des bouquins papier.
Du coup, j'ai pensé à une autre solution,
officiellement bien plus adapté pour écrire des livres.
--

[#docbook-ex-1]
Il y en a qui reconnaissent ça ?
Il y en a qui aime écrire avec ça ?

[#docbook]
--
Ça, c'est du DocBook.
DocBook, c'est un schéma XML très structuré et sémantique qui insiste sur la séparation contenu et présentation.
Du coup ça a l'air bien en principe,
mais un peu comme avec l'HTML,
--

[#docbook-ex-2]
--
il faut glisser le contenu au travers d'une quantité astronomique de balises.
Je me vois mal demander à mon père d'apprendre toute cette structure.
#TROLL inside#
Il a déjà fait 16 ans d'études, est-ce qu'il méritent vraiment de subir l'apprentissage d'XML plus toutes les balises de DocBook ?

// The ironic part is that the engineer didn't do herself much of a favor either.
// XML tools--especially the ones used in the DocBook toolchain, such as XSLT--are a pain to work with.

// Nobody wins.
//SAW: visual concept - image meme opposite of winning
Moi, j'ai pas fait 16 ans d'études mais je me souviens que beaucoup de mes profs étaient aussi des chercheurs et ils utilisaient ça :
--

[#latex-ex-1]
Bon clairement, les techos qui ont inventé ça se sont fait plaisir pendant que les écrivains étaient partis.
Ça, c'est LaTeX !

[#latex]
LaTeX est un langage et un système de composition de documents.
On le connait bien pour l'attention qu'il porte à la typographie.
Il a aussi eu beaucoup de succès dans les milieux académiques et scientifiques pour sa gestion des formules.

[#latex-ex-2]
--
Le problème c'est que mon contenu n'est toujours pas le roi.
On a encore une fois beaucoup de trop d'informations en plus du texte.
En plus, le système est prévu à la base uniquement pour sortir du PDF.
Il n'a pas été pensé pour le Web ou d'autres médias.
Les options sont limitées avant même d'avoir commencé.
// !!! LaTeX have many differences and dialects

// The message here--if you can even interpret it--is:
// "`I don't really see the difference between content, typesetting, and presentation, so I'll just mash all these concerns together.`"

// Writers get lost in this syntax, not only because it looks like a bird nest, but now there's this deluge of dialects no mere mortal can possibly remember.
//SAW: image concept - labrynth/maze which matches the "get lost" concept
--

[#asciidoc-preamble]
--
Du coup je fais quoi, j'abandonne ?
On vient de voir plein de solutions pour séparer le contenu et la présentation,
mais il y en a aucune que j'ai envie de proposer à mon père ou que je me vois utiliser pour ma doc ou mon blog.
La plupart de ses solutions ne mettent pas en avant l'écrivain qui sommeille en nous.

#voix triomphante#

Cette situation *doit* changer !
Laissez moi vous présenter AsciiDoc.
--

[#asciidoc-ex]
Aaaaahhh...
Mes contenus respirent un peu là.
Ça fait du bien pour la relecture mais aussi à l'écriture.

[#asciidoc]
AsciiDoc a été créé en 2002 comme étant un système de markup dédié pour ceux qui écrivent et ce quel que soit le type de contenu.
#énergique#
Quand j'ai montré ça à mon père il a désinstallé Word dans la seconde.
Non je déconne, mais il était intrigué...
L'idée d'avoir des annotations simples et explicites plutôt que d'appliquer les conventions de son éditeur lui plaisait beaucoup.
Une des rares choses qui l'inquiétait c'est la petite phase d'apprentissage.

[#asciidoc-ex]
--
Mais en fait qu'en on regarde de plus près, il n'y a pas grand chose.
La syntaxe est claire et concise.

Asciidoc
  clair & concis
    ex: général

//LAR: Can we have a series of example slides as you go through this list of benefits?
//LAR: That would be more informative and engaging.
//LAR: I'm not wild about the highlighted list because it isn't "showing" what you're talking about, which is the point, right?
//LAR: Slides that show the AsciiDoc version and what is created (like the reference manual) would be great.
The first thing you'll notice about AsciiDoc is that the syntax is clear & concise.
//LAR: a slide here of the syntax that shows what you mean.
What you see is predominantly content.
It's readable in raw form, unlike the other formats we've seen thus far.

//LAR: Is this quote necessary?
//LAR: Maybe make it a slide and move it to the end of this section?
//SAW: Agree with LAR, the quote, while applicable, isn't needed and probably breaks the flow of the narrative.
//"#Perfection is achieved not when there's nothing more to add, but when there's nothing left to take away.#"
//-- Antoine de Saint-Exubéry

Paragraphs are just paragraphs, no bullshit.
//LAR: give me an example slide.
The remaining marks are based on familiar conventions, such as leading asterisks to itemize a list, asterisks or underscores around a phrase to emphasize it, and leading equal signs to designate a section title.
//LAR: another slide example.
Keywords that appear in the syntax are based on common terminology such as `image`, `video`, and `source`.

And the syntax is remarkably forgiving, which makes it less daunting for first timers.

If you dig deeper, you'll notice a consistency to the syntax.
That's because the language is based on repeatable patterns.
Extensions further build on these patterns, which we'll get into later.

Finally, the syntax is extremely semantic.
In fact, AsciiDoc was originally designed as a shorthand for DocBook.
Each bit of content belongs to a node--a content block or phrase.
Nodes can be annotated with extra bits of information that state what the content is, how it might be presented, and other properties.
//SAW: we definitely want an example slide of this.
--

[#ex-paragraphs]
--
Un paragraphe n'est rien d'autre qu'une suite de lignes de texte.

Pour un nouveau paragraphe, il suffit d'une ligne vide.

Ça permet du coup de mettre une phrase par ligne.
(TODO) avantages
--

[#ex-sections]
--
Pour les titres, on utilise autant de = (ou de #) que le niveau de la section.
--

[#ex-lists-ul]
--
Les conventions sont assez familières.
Pour des listes à puces, on utilise des astérisques,
un peu comme ce qu'on aurait fait sur une feuille de papier.
--

[#ex-lists-ol]
--
Pour les listes ordonnées, on met juste un point,
le système se chargera de les numéroter.
Du coup on ne mélange pas le contenu avec la numérotation qui sera choisie à l'impression :
a), b), c)
1., 2., 3.
--

[#ex-formatting]
--
Le seule truc à retenir, c'est pour le formattage.

* Pour le gras, on encadre avec des astérisques
* Pour l'italique, on encadre avec des underscores (tiret du 8)
* Pour les mots clé, on encadre avec des backticks
* Mais on peut aussi avec des dièses définir ses propres types de format
--

[#ex-multimedia]
--
La terminologie est claire et consistante.
Pour une image, c'est *image*, c'est pas *!()[]*.
Pour video, c'est video, pour icone : icone, etc...
--

[#left-aligned-lines]
--
syntax souple (forgiving)
sémantique
left-aligned

One reason the syntax is so simple and consistent is because it’s both line-oriented and left-aligned.
--

[#ex-roles]
--
terminologie commune
  ex: image, video, source
  consistence, pattern répétés et extensions

The most versatile semantic information is the role.

Roles serve a very important purpose in the AsciiDoc syntax because they allow the writer to pass information to the publisher about the semantics of a node without having to worry how it gets formatted.
The role basically says "`this element has special significance, you deal with it.`"
This abtraction, and other such metadata, is central to achieving the separation of content and presentation.
The writer gets to focus on what the content is saying, not how it looks.
--

[#ex-delimited-block]
--
terminologie commune
  ex: image, video, source
  consistence, pattern répétés et extensions

Having a syntax that's aligned to the left margin helps keeps the writer rooted.
You don't have to worry how much indentation you need and content doesn't float out into the ether.
Instead, you rely on delimiter lines, or "`fences`" to encompass the content.
AsciiDoc can then assume everything between those lines is content that belongs to that block.

//The line-oriented arrangement takes advantage of the fact that source code is organized in lines.
//A lot can be inferred from a line break in the content.
The line-oriented arrangements allows us use the line break to imply meaning.
A line often serves as the boundaries of a node.
Consecutive lines that start with an asterisk, for instance, are clearly items in a list.
A line above a block that starts with a period is the block's title.
We do the same thing when writing code.
Each statement gets its own line, so there's no need for a semicolon to separate statements.
--

[#wysiwyg]
// So, what's absent here?
// WYSIWYG.
Comme vient de le montrer Ludo,
Pas de WYSIWYG, mais est ce que c'est vraiment une perte ?
Je passe plus de temps à me battre avec les barres d'outils de Word, de CMS et autres Wikis qui proposent ça que de réfléchir à ce que je veux écrire.
En fait, comme dirait mon collègue Dan,
c'est plutôt :

[#ygwyg]
--
What You Get Is What You Get :-(
// But is it really a problem?
// Yeah, I don't think so.
//I'm here to tell you that you don't need it.
// WYSIWYG places a barrier between you and your content and robs you of a lot of control.
// Unfortunately, it's an all too familiar input mechanism in a CMS.
// We should really call a CMS a content lobotomy system, or CLS.
// Instead of suiting your needs, it _seemingly_ solves your problem by making it impossible to do what you want to do.
// I like to say, "`You Get What You Get.`"
//alt: What You Get Is What You Get (WYGIWYG)

// AsciiDoc, on the other hand, is readable in raw form and there's no curtain between you and your content.
// But that doesn't mean that you can't make it look pretty.
Avec Asciidoc on a le texte et le markup.
Rien n'est caché mais ça veut pas dire que la sortie sera moche bien au contraire.

// AsciiDoc has a rich syntax, with many, _many_ built-in elements and options to organize and annotate your content.
// You shouldn't expect to learn it all in one day.
// But you also don't have to.

// Most shops gravitate towards a subset of the markup.
// Dialects, particularly using roles, naturally emerge that bring additional consistency and reinforce the impression of simplicity.
---
Ce que j'aime vraiment avec AsciiDoc, c'est qu'il a une syntaxe riche qui répond à la majeure partie des besoins d'un auteur pour annoter et organiser ses contenus.
OK, ça ne s'apprend pas en 5 minutes,
mais c'est pas grave et c'est normal.
On peut très facilement commencer avec les bases, les besoins complexes viennent par la suite.
--

[#creation-recommended-practices]
--
Si vous le mettez en place en place chez vous,
n'hésitez pas à partager un *document exemple* qui met en avant la plupart des syntaxes utiles pour votre contexte.
// See http://www.winglemeyer.org/technology/2016/09/08/semantic-asciidoc/
// You can prepare templates for common document types to help give writers an easy starting point.
Et surtout : réutilisez vos pratiques de codeurs préférées !!!
--


[#dry]
--
Ludo l'a bien montré,
---
Avec les includes, on va pouvoir découper un document en plusieurs fichiers (1 par chapitre ou section).
Tjs avec les includes on va pouvoir éviter les copier/coller et inclure des exemples de code qui viennent directement des sources ou bien de fichiers dédiés.
Ça allége un peu le document et surtout en ayant vos sources dans des fichiers *.js* ou *.java*, vous êtes certain que le code présent dans la doc est à jour, qu'il est testé, linté et qu'il compile.
---
L'utilisation des variables permet également de ne pas se répéter et d'assurer une documentation à jour.
---
En plus des pratiques, avec AsciiDoc on peut enfin utiliser sereinement les mêmes outils pour le code et pour les contenus.
--

[#atom]
--
//(If there's time: Discuss authoring in Atom with the AsciiDoc add-on to get helpful syntax highlighting.
//Also mention AsciidocFX and IntelliJ IDEA.)
// Play on IntelliJ logo; "Write with Pleasure"
--

[#ide-for-writers]
--
La démo de Ludo est un super exemple qui prouve qu'un éditeur de code comme Atom,
avec les bons plugins,
est pas loin de devenir un vrai IDE pour auteurs de contenus.

Moi j'utilise à fond :

* Coloration syntaxique
* Autocomplétion
* Multi-cursor
* et c'est que le début...
// Using a text editor such as Atom with the appropriate add-ons, you can see the final product in a preview pane.
// //alt: see how it's going to look in a preview pane
// As you can change, embellish, or restructure the document, you can see what the end result is going to look like in real time.
//
// I do believe tools such as Atom can go much further...maturing into a full blown IDE for writers.
// //Efforts are underway.
// Imagine Alt+Enter for synonyms.
// We're not that far away.
--

[#ex-includes]
// DA: TODO it feels like we should mention cross references here
Another way to simplify writing with AsciiDoc is to partition large documents.
For instance, you can split up the source of a book along chapter divisions.
You can also import common content or extracted code samples so they don't clutter the writer's view.
AsciiDoc supports all this through its include mechanism.
You can even include portions of another document by selecting the snippets by line number or tag.
//DA: TODO recommend checking out the AsciiDoc Syntax Quick Reference and Awesome Asciidoctor.

////
//DA: FIXME the topic of migration feels like it should be somewhere else
//DA: PSA about pandoc

[#migration]
I'm not going to get into how to migrate your existing content to AsciiDoc today, but be aware it is possible.
There are conversion tools, and many others have made the switch successfully.
See me afterward and I can give you some pointers.
////

[#dawn]
--
Après avoir expliqué à mon père tous les avantages du concept de *documentation as code* et à quel point AsciiDoc ça déchire il était : intrigué.
C'est une première étape ?
Après tout, il est pas développeur, c'est normal qu'il soit pas convaincu à 100% en 20min.
// Now that the content is encoded in AsciiDoc, who does the writer hand it off to and what can be done with it?
//
// The AsciiDoc syntax is so simple and elegant, it's easy to be deceived that it can only produce primitive output.
// That couldn't be further from the truth.
// The AsciiDoc content is just the raw material and its semantics are the seeds of the blossoms we'll produce.
// This is where engineers get to work their magic.
//
// Let's shed some light on how we can transform it and where we can publish it.
// It's the dawn of endless possibilities, just like The Print Shop was for me as a child.
--


[#collaboration]
--
Du coup, ensuite j'ai voulu parler de collaboration.
J'ai encore du mal à me remettre du fait qu'il utilise des *marques de révisions* de Word et des échanges par email avec son éditeur.

Il faut que je lui montre comment nous les codeurs on collabore entre nous.
// We've arrived at the final section of this talk: collaboration.
// This section addresses both the writers and the engineers, as well as anyone else who must work side-by-side to produce technical content.
// This is where the harmony of writing and delivery comes together.
//
// AsciiDoc lends itself well to collaboration because many of the tools needed to collaborate on it are already in place in a development shop.
// In particular, AsciiDoc is ripe for collaboration because it's source control friendly.
--

[#git]
--
Il faut que je le forme a git !!!
#hésitation#
ok, fausse bonne idée.
Du coup j'ai tenté un mode *par l'exemple* pour lui montrer comment on utilise git pour collaborer.

Et c'est là que c'est génial.
AsciiDoc ne réinvente pas là roue.
Il vient pas avec son propre système d'historique de versions comme peuvent l'avoir pas mal de CMS ou de wikis.
Par contre, étant donné que c'est juste du texte,
--

// [#redhat-endorsement-1]
// --
// This is a real force for contribution, as the JBoss BxMS and OpenShift teams can attest to.
//
// _(refer to quote in slide)_
// --

[#source-control]
on va pouvoir l'utiliser avec git sans soucis.
Grâce à ça, on a l'historique des modifications,
les diffs entre différentes versions,
des branches de travail etc...
Et puis en plus, on va pouvoir utiliser ça avec n'importe quelle interface Web GitHub, GitLab, bitbucket...
// AsciiDoc doesn't specifically have "`source control support.`"
// Instead, it simply lends itself to being source controlled.
// No binary blobs, just plain text.
// And source control systems like git just _love_ plain text.
// You get history, source diffs, rich diffs, branching, merging, etc., all which can be managed through interfaces like GitHub, GitLab, and Bitbucket.

[#edit-on-github]
--
It's hard to overstate the significance of GitHub (and, increasingly, GitLab) for collaboration.
These interfaces have proven to be incredibly approachable and to encourage contribution.

Nothing is a stronger force for inviting participation than an "`Edit on GitHub`" link in your docs.
It presents any page as editable, yet funnels the contributor into a web-based content review workflow based on git.
The web-based editor recognizes AsciiDoc and can show a preview of it.

As an aside, if you take this route, I strongly recommend investing in git training.
Everyone on the team needs to understand how the git workflow behind the "`Edit on GitHub`" link works to truly benefit from it.
And, trust me, knowing how to use git correctly will save time and toes.
--

[#ss-github-rendered-file]
--
sur GitHub par exemple, on a le rendu.
--

[#ss-github-edit-file-button]
--
(TODO)
--

[#ss-github-edit-file]
--
(TODO)
--

[#ss-github-preview-changes]
--
(TODO)
--

[#ss-github-commit-changes]
--
(TODO)
--

[#docs-as-code]
--
// DA: Think Wikipedia for your docs, backed by git.
// HS:
Comme un Wiki mais en mieux !

Edition hors ligne
Edition dans un IDE spécialé
Colocaliser le code et sa doc

si vous avez une documentation technique open source, c'est encore mieux
à défaut d'avoir des contributions conséquence au aurez au moins peut-être la change d'avoir des corrections pour les fautes d'orthographe

// What is a wiki, after all.
// It's for writing in some sort of markup language that you can edit on the web.
// We have all the advantages of a wiki, like Wikipedia, but it's also backed by git.
// You can benefit from the social coding phenomenon simply by moving your documentation to one of these platforms.

// All this leads to a strong-held belief of ours.
// Docs = Code.

We have a long history in this industry of collaborating on code.
If we view documentation as just another form of code, we can use code collaboration processes, practices, techniques, and tools to benefit our documentation.
Strength building on strength for a solid end product.
--

[#mulesoft-github-01]
--
How many CMS tools have tried to manufacture a content review workflow?
Well, we have one right here, built on an accepted industry practice of code review and supported by incredible tools like Gerrit, GitHub, GitLab, and so forth.

This system is also makes it easy for managers to monitor the workflow, determine what changed or track what work was done just by browsing the git history or studying the activity charts on GitHub or GitLab.
--

[#ss-source-diff]
--
(TODO)
--

[#ss-rich-diff]
--
(TODO)
--

[#ss-code-review]
--
(TODO)
--


[#collaboration-recommended-practices]
--
AsciiDoc est vraiment fait pour bien fonctionner avec git mais il y plusieurs choses que vous pouvez faire pour améliorer votre collaboration.
// While AsciiDoc is naturally friendly to source control systems, there are some things you can do to optimize collaboration.

//* Keep changes isolated
//* Modularize the content
//* Avoid micro-migrations by using validation tools and a style guide
//* Plan content changes in an issue tracker
//* Manage different versions in branches
//* Provide an automated build

//In general, you want to look for ways that allow you to work in different parts of a file without causing conflicts.
---
Essayez de bien isoler les changements.
* Une phrase par ligne
** Meilleurs diffs
** Merges plus faciles
// One way to do this is by writing using the sentence-per-line method.
// Changes to a sentence do not affect the sentences around it (much like code), and therefore prevents people from step on each other's commits.

// You also don't want documents that are too large, so modularize your content and break up monolithic documents.
//In particular, beware of the Russian Doll Effect (contributing guide inside developer guide inside of README).
//It's easy to create a script that brings them all back together.
// People can then work on different parts of the documentation without having to coordinate.
// As mentioned earlier, import non-content such as code snippets so it can be managed independently and kept up to date.
//Don't fall into the trap of putting all your content in a single repository.
//Instead, organize your repositories by software product or logical product group.
//We can refer to this repository as a "`content container.`" (a contrast to a "`library layout`" where there's one directory per book).

// Use validation tools to catch writing errors early and drastically cut down on expense micro-migrations to fix these mistakes.
// It helps to have a style guide so information is organized consistently without having to do a lot of personal training.
--

[#issue-tracker]
--
Use an issue tracker to manage bugs, improvements, and content initiatives.
You can then see content progress as it moves across the issue board.
--

[#pull-request]
--
Discutez, échangez, corrigez, éditez...
Mention the issue when submitting the pull request that resolves it.
Just like code.

How many CMS tools have tried to manufacture a content review workflow?
Well, we have one right here, built on an accepted industry practice of code review and supported by incredible tools like Gerrit, GitHub, GitLab, and so forth.

This system is also makes it easy for managers to monitor the workflow, determine what changed or track what work was done just by browsing the git history or studying the activity charts on GitHub or GitLab.
--

[#content-review]
--
Faites des vraies revue de contenus.
---
Style guide
tjs le même mot pour le même terme
tutoiement, vouvoiement, 3ème personne
--

[#working-branches]
--
utilisez les branches pour essayer des idées
pour travailler à plusieurs en même tps
ou sur plusieurs parties en même tps
---
Essayez de bien découper et découpler les différentes parties de votre doc
* En fonction des projets on va pouvoir
** Mettre la doc au même endroit que le code
** Repos dédiés
** Plusieurs répos dédiés
---

It's best to manage different versions of a document using branches so you can take advantage of the tools the source control system gives you.
//You can then assume that all the content in a single repository is versioned together.
// To help with this, organize your repositories by software product or logical product group.
//Don't use different directories to store the versions, as I've seen some teams do.
// Then, have a branch for each major release line.
// If different documents have different versioning schemes, or move at different rates, that's an indicator you should move them to separate repositories.
//Take a look at AsciiBinder for an example of a build system that builds out versions of the documentation from the branches.

// Regardless of how you structure and organize the content, anyone coming along should be able to build the output through a simple interface, without having to remember complex commands.
// This is the role of an automated "`development`" build.
// It makes the documentation approachable and allows contributors to verify the changes they make improve the product in the way they expect (and not the opposite).
// The documentation can also be staged for review by different groups.

// As you can see, AsciiDoc allows you to set up many ways to collaborate, bringing all the voices and talents together in one place to make strong, coherent documentation.
--

[#publication-preamble]
--
AsciiDoc et git vont super bien en ensemble pour collaborer.
On a bcp parlé d'écrire la doc mais c'est tout aussi vrai pour la maintenance d'une grosse documentation dans le temps.
C'est là où le bug tracker, et l'historique des commits apportent beaucoup de valeur.
---
Bon du coup, sur cette partie, je pense que mon père a saisi les avantages d'utiliser toutes ces pratiques mais ça faisait beaucoup à la fois.
En plus, quel que soit votre projet, je vous conseille d'investir dans une bonne formation git pour l'ensemble des personnes qui toucheront à la doc.
---
--

[#publication]
Le dernier point que j'ai abordé avec mon père, c'est la publication.
Je me suis pas beaucoup attardé dessus avec lui car techiquement, c'est son éditeur qui s'occupe de publier ses livres papier et numériques.
Par contre, avec vous on va pouvoir rentrer dans les détails et parler d'asciidoctor.

[#asciidoc-vs-asciidoctor]
--
It's important to first get some terminology out of the way.

AsciiDoc is the language.
Asciidoctor is the processor.

We've seen AsciiDoc already.
So what can the processor do?
--

[#conversion]
--
Right out of the box, Asciidoctor can convert AsciiDoc to HTML and DocBook, giving you the ability to preview or export your content, respectively.
But that's just the default interpretation of the AsciiDoc source.
There's nothing stopping you from interpreting the source in a different way.

Every bit of output generated by Asciidoctor can be customized.
That's what the separation of content and presentation affords you.
--

//LAR: it would be good to have slide examples of these
[#ex-extensions]
--
I'll cite a few examples to get you thinking about what is possible.

* nested blocks to make a tab component (#TODO show example#)
* image macro that serves as background image
* slide notes
* import a PDF page

You should view AsciiDoc more as a source of record, not a textual representation of the output.
--

[#ast]
--
The bridge to get from content to presentation--you might even say the magic trick--is transformation.
Transformation is the key to being able to publish to a variety of formats and variants of those formats.
Let's dive into how transformation works.

When Asciidoctor reads in the file, it builds an AST, short for abstract syntax tree.
That tree gets passed to a converter, which then transforms the structure into a target format, such as HTML, or some application of HTML, like slides.
This presentation, in fact, is the product of that transformation.

One way to extend Asciidoctor is to write a custom converter--as was used for this presentation--or tweak one that already exists by supplying custom templates.
The only limit to what output formats you can produce is what you're willing and able to create.

Even before the tree is sent to the converter, you have a chance to manipulate it using a tree processor.
In fact, you don't even have to output anything.
You can just use the AST to query the document for information in a contextual way (unlike grep, which is crude and blind to context).

You can go a step further and enhance the parser itself.
Asciidoctor provides an extension API for introducing additional elements into the syntax, such as a custom block or macro.
This is where things gets really exciting.

#TODO talk about lorem block macro example#

As you can see, you have a lot of control over how the AsciiDoc is interpreted.
--

[#aggregate]
--
Be careful not to fall into the trap of thinking that one input document produces one output document.
The integration of multiple sources of content into numerous publishing targets is one of the key strengths of Asciidoctor.

For example, you can take one input document that represents a book and produce multiple pages of HTML.
Reasonable enough.
Or, you can use the processor, or a toolchain that wraps it, to weave together input from several sources.

We see this technique used in API documentation tools like Spring REST Docs and swagger2markup, which generate AsciiDoc to document the API methods, then combine that generated content with content written by the author to form a final document (or documents) to be published.
You can also weave in content that gets derived from the source code, such as a configuration property table.
Part generated, part scribed.
//The toolchain plays the role of orchestrator, weaving together disparate content sources.
--

[#endless-possibilities]
--
This transformation capability also prevents lock-in.
Just as you can generate formats for publishing, you can convert to another source format, even AsciiDoc itself.
There truly are endless possibilities for your content once it's in the AsciiDoc format and fed into this toolchain.

//If you store the source in a source control system, which we'll talk more about in the next section.
//The publication tool can even tap into the document history and inject content such as an audit log or make different versions of the document available.
//This is another powerful way to keep your content DRY and free from doing tasks for information that can be implied.
//You could extend the abstraction even further and avoid coupling the path of the source file with the output path.
//Instead, give each document a business ID so you can move files around and still produce the same output structure.
--

[#whos-using-asciidoc.SLIDE.tpl-media.contain]
--
* Oreilly
** Modular JavaScript (N. Bevaqua)
** Elastic search Definitive Guide
* Redhat
** OpenShift
** Hibernate
* Pivotal
** Spring
** Grails
* Neo4j
* Datastax
* git
* Ninja Squad book
* MuleSoft
* infoQ minibooks
--

[#push-to-publish]
--
Processing doesn't end with Asciidoctor.
The whole publication phase should be managed by a build and fully automated.
Just like in our childhood print shop, once we sent our masterpiece to the printer, it took over publishing from there.
I like to call this "`push to publish.`"
It's the modern day "`send it off to the printer.`"
We're also borrowing a page from development by implementing continuous delivery for the documentation.

//The build should not only handle converting the content and publishing it to the various channels, but should describe and manage the infrastructure as well.
Treat your docs just like you would any other application.
These automated builds also aid with collaboration, which we'll launch into next.
//Anyone should be able to build the documentation for local preview.
//The documentation can also be staged for review by different groups.
--

[#recap-story]
--
#musique au coin du feu#
🗣 En rentrant lui, notre héro était...
--

[#recap-story-sad]
--
...un peu blasé.
🗣 Il repensait à tout ce qu'il venait d'expliquer à son père.
🗣 Cela faisait peut-être beaucoup d'informations en une seule fois :
nouveau outils, nouvelles approches et nouvelles techniques.
🗣 Il savait pertinemment que son père allait continuer à utiliser Word et des emails pour écrire ses livres.
--

[#recap-story-happy]
--
🗣 Par contre il était persuadé qu'il pouvait convainvre et changer les habitudes de ceux qui codent : *VOUS !*
🗣 *Vous* avez déjà les outils et les pratiques pour l'écriture, la maintenance, la collaboration et la publication de votre code,
--

[#recap-story-love]
#presque alexandrin#
🗣 il ne vous reste plus qu'à vous emparer d'Asciidoc et d'asciidoctor
🗣 pour traiter votre documentation avec la même passion.

[#fin]
--
Merci bcp.
--

// [#publication-recommended-practices]
// --
// (TODO)
// --


no wysiwyg
  CMS pb
you get what you get
  CMS, wikis

IDE for writers
  stop thinking about what we had before and
  think about tools

Atom
* un peu de syntaxe
* insister sur la coloration
** coloration syntaxique de code block
* mode preview pdt toute la présentation
* "WHAT ELSE COULD WE DO?"
* quelques techniques de codeurs
** variables/attributes
** includes
** autocomplétion
** réordonner des lignes
** multicursors
** search & replace (regexs)
** ...autres
//* zen mode

// à trier
roles ?
1 sentence per line (maybe collaboration)
footnote ?
